import { BrandMarquee } from '@/components/brand-marquee';
import { HistoryClosing } from '@/components/history-closing';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { StoryboardScroll } from '@/components/storyboard-scroll';

export const metadata={title:'Nuestra historia — Grupo Sarabia | GS3'};
const H='/assets/history-';
function Asset({name,width,height,alt='',className=''}:{name:string;width:number;height:number;alt?:string;className?:string}){return <img className={className} src={`${H}${name}`} width={width} height={height} alt={alt}/>}
export default function HistoryPage(){return <><SiteHeader/><main className="about-page"><section className="group-intro"><div className="group-hero"><div className="group-copy"><div className="sarabia-group" role="img" aria-label="Grupo Sarabia"><Asset name="imgIso.svg" width={99.392} height={56.059} className="sarabia-symbol"/><Asset name="imgGroup90.svg" width={71.392} height={6.452} className="sarabia-group-name"/><Asset name="imgGroup91.svg" width={115.605} height={20.163} className="sarabia-lettering"/></div><h1><span>Vivimos el agro.</span> Somos un grupo familiar que hizo de la confianza y el compromiso la base de su historia en el agro.</h1></div><div className="group-map-crop"><Asset name="imgGroup92.svg" width={1262.12} height={1314.79} alt="Presencia del Grupo Sarabia en América del Sur" className="group-map"/></div></div><BrandMarquee><div className="group-brands"><div><p>Industria</p><div className="brand-lockup"><Asset name="imgGroup.svg" width={30.164} height={33.097}/><Asset name="imgGroup1.svg" width={90.693} height={17.286} alt="Tecnomyl"/></div></div><div><p>Distribución</p><Asset name="imgGroup2.svg" width={127.526} height={32.098} alt="Agrofertil"/></div><div><p>Tecnología</p><div className="brand-lockup"><div className="h2o-logo" role="img" aria-label="H2O"><Asset name="imgGroup3.svg" width={41} height={4.4} className="h2o-1"/><Asset name="imgGroup4.svg" width={41} height={16.4} className="h2o-2"/><Asset name="imgVector.svg" width={33.4} height={33} className="h2o-3"/><Asset name="imgGroup5.svg" width={27.2} height={27} className="h2o-4"/></div><Asset name="imgYvy.svg" width={74.408} height={24.35} alt="YVY"/></div></div><div><p>Producción</p><div className="brand-lockup"><Asset name="imgAgropecuariaCataratas.svg" width={116} height={34} alt="Agropecuaria Cataratas"/><Asset name="imgCapa1.svg" width={116} height={34} alt="Campos Nuevos"/></div></div><div><p>Social</p><div className="brand-lockup"><span className="social-brand sieg" role="img" aria-label="SIEG"/><span className="social-brand foundation" role="img" aria-label="Fundación Sarabia"/></div></div></div></BrandMarquee></section><StoryboardScroll/><div className="bottom-wrap"><HistoryClosing/><SiteFooter/></div></main></>}
