const A = '/assets/';
function Action({ href, children, filled = false }: { href: string; children: React.ReactNode; filled?: boolean }) {
  return <a className={`action${filled ? ' action-filled' : ''}`} href={href}>{children}<img src={`${A}arrow-${filled ? 'white' : 'green'}.svg`} width="20" height="20" alt="" /></a>;
}
export default function Home() {
  return <>
    <a className="skip-link" href="#contenido">Saltar al contenido</a>
    <header className="header"><a href="#" aria-label="GS3 — Inicio"><img src={`${A}logo.svg`} width="112" height="28" alt="GS3" /></a></header>
    <main id="contenido">
      <section className="hero" aria-labelledby="hero-title">
        <div className="hero-copy"><h1 id="hero-title"><span>Mucho más que crédito.</span> Un parceiro del productor</h1><div className="hero-description"><p>Conocemos lo que implica producir porque también venimos del campo. Por eso, facilitamos el acceso al crédito con una atención ágil, cercana y pensada para la realidad del agro.</p><Action href="#servicios">Nuestros Servicios</Action></div></div>
        <div className="hero-image"><img src={`${A}hero.png`} alt="Dos generaciones de productores junto al campo al atardecer" fetchPriority="high" /></div>
      </section>
      <section className="solutions" id="servicios" aria-labelledby="solutions-title">
        <h2 id="solutions-title">Soluciones financieras<br /><span>con los valores del campo,</span><br />para cada etapa del ciclo productivo.</h2>
        <div className="service-row"><div className="landscape-image"><img src={`${A}landscape.png`} alt="Paisaje agrícola con cultivos y campos productivos" loading="lazy" /></div><div className="service-copy"><h3>Del crédito al financiamiento de la zafra</h3><p>Soluciones financieras para responder a las necesidades de tu producción, desde la planificación hasta el cierre de la campaña.</p><Action href="mailto:contacto@gs3.com.py?subject=Consulta%20sobre%20servicios">Nuestros Servicios</Action></div></div>
        <div className="values"><article><div className="value-image"><img src={`${A}integrity.png`} alt="Productores conversando durante la cosecha" loading="lazy" /></div><h3>Fe para actuar con integridad</h3><p>Tomamos cada decisión con responsabilidad, respeto y conciencia de su impacto.</p></article><article><div className="value-image family-image"><img src={`${A}family.png`} alt="Una familia de productores junto a su cosechadora" loading="lazy" /></div><div className="family-copy"><h3>Familia para valorar lo que realmente importa</h3><p>Construimos relaciones duraderas, basadas en la confianza, la cooperación y el compromiso con quienes nos rodean.</p></div></article></div>
      </section>
      <div className="bottom-wrap"><section className="history" id="historia" aria-labelledby="history-title"><img className="history-background" src={`${A}field.png`} alt="" loading="lazy" /><img className="history-curve" src={`${A}curve.svg`} alt="" loading="lazy" /><div className="history-content"><img className="sarabia" src={`${A}sarabia.svg`} width="114" height="64" alt="Grupo Sarabia" /><div><p className="overline">Somos una empresa del Grupo Sarabia</p><h2 id="history-title">Más de 30 años de experiencia en el agro respaldan nuestro conocimiento del campo</h2></div><Action href="mailto:contacto@gs3.com.py?subject=Conocer%20la%20historia%20de%20GS3" filled>Nuestra historia</Action></div></section>
      <footer><img className="footer-watermark" src={`${A}watermark.svg`} alt="" loading="lazy" /><img className="footer-logo" src={`${A}logo-footer.svg`} width="163" height="40" alt="GS3" /><div className="footer-columns"><div><div className="footer-group"><h2>Transparencia</h2>{['Política de Riesgos Integrales','Política de Crédito','Política de Privacidad','Código de Ética y Conducta','PLD/FT','Canal de Denuncias'].map(label=><a key={label} href={`mailto:contacto@gs3.com.py?subject=${encodeURIComponent(label)}`}>{label}</a>)}</div><div className="footer-group social"><h2>Redes Sociales</h2><div className="social-icons">{['Facebook','Instagram','YouTube','LinkedIn'].map((name,i)=><span key={name} title={name}><img src={`${A}social-${i+1}.svg`} width="24" height="24" alt={name} /></span>)}</div></div></div><div><div className="footer-group"><h2>Hable con nosotros</h2><a className="contact" href="mailto:contacto@gs3.com.py">contacto@gs3.com.py</a></div><div className="footer-group talent"><h2>Talento</h2><a href="mailto:contacto@gs3.com.py?subject=Trabaje%20con%20nosotros">Trabaje con nosotros</a></div></div><div className="footer-group"><h2>Informes</h2>{['Reportes Semestrales','Tasas'].map(label=><a key={label} href={`mailto:contacto@gs3.com.py?subject=${encodeURIComponent(label)}`}>{label}</a>)}</div></div><small>© 2026 GS3 S.A. — Todos los derechos reservados.</small></footer></div>
    </main>
  </>;
}
