import text from '@/lib/extra-content.json';

export function ReportsContent(){
 const a=text.reports;
 return <><section className="management"><h2>{a[2]}</h2><p>{a[3]}</p><p>{a[5]}</p><div className="people-grid directors">{[[a[6],a[7]],[a[8],a[9]],[a[10],a[11]]].map(([role,name])=><article key={name}><span>{role}</span><h3>{name}</h3></article>)}</div></section><section className="management"><h2>{a[12]}</h2><p>{a[13]}</p><div className="people-grid">{[[a[14],a[15]],[a[16],a[17]],[a[18],a[19]],[a[20],a[21]]].map(([role,name])=><article key={name}><span>{role}</span><h3>{name}</h3></article>)}</div></section><div className="policy-sections">{[[a[22],a[23]],[a[24],a[25]]].map(([title,body])=><section className="policy-row" key={title}><h2>{title}</h2><p>{body}</p></section>)}</div><section className="principles"><h2>{a[26]}</h2><div className="principle-grid">{[[a[27],a[28]],[a[29],a[30]],[a[31],a[32]],[a[33],a[34]]].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section></>;
}
export function ComplaintsContent(){
 const a=text.complaints;
 const guarantees=[['shield','Confidencialidad','La identidad del denunciante será protegida.'],['anonymous','Anonimato','Es posible realizar denuncias de forma anónima.'],['voice','No represalia','Ningún denunciante sufrirá represalias por reportar una conducta indebida.'],['investigation','Investigación','Toda denuncia será investigada por el Comité de Ética.']];
 return <><div className="policy-intro"><p>{a[2]}</p><p>{a[4]}</p></div><section className="guarantees"><h2>Garantías del Canal</h2><div className="guarantee-grid">{guarantees.map(([icon,title,body])=><article key={icon}><img src={`/assets/${icon}.svg`} width="24" height="24" alt=""/><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section><section className="faq"><h2>Preguntas frecuentes</h2><div className="policy-row"><h3>¿Qué se puede reportar?</h3><div>{a.slice(16,22).map((p,i)=><p key={i}>{p}</p>)}</div></div><div className="policy-row"><h3>Cómo reportar</h3><div><p>Las denuncias y reclamos pueden presentarse a través de los siguientes canales:</p><div className="report-channels"><article><h4>Formulario web</h4><span className="muted">Próximamente</span></article><article><h4>Correo electrónico</h4><span>denuncias@gs3.com.py<br/>cumplimiento@gs3.com.py</span></article><article><h4>Correo postal</h4><span>Avenida Aviadores del Chaco Nro. 3301 - Asunción, Paraguay</span></article></div></div></div><div className="policy-row"><h3>¿Qué es el Canal de Denuncias?</h3><div><p>{a[2]}</p><p>{a[4]}</p><form className="complaint-form" aria-describedby="form-unavailable"><h2>Hablemos</h2><p>Completá el formulario y nuestro equipo se comunicará contigo.</p><fieldset disabled><div className="form-grid"><label>Nombre Completo<input placeholder="Nombre completo" autoComplete="name" /></label><label>Correo Electrónico<input type="email" placeholder="Correo electrónico" autoComplete="email" /></label><label>Empresa / Razón Social<input placeholder="Empresa" autoComplete="organization" /></label><label>Teléfono / WhatsApp<input type="tel" placeholder="Teléfono" autoComplete="tel" /></label><label className="form-full">Asunto<input placeholder="Describa el asunto" /></label><label className="form-full">Mensaje<textarea placeholder="Deje su mensaje…" rows={5} /></label></div><label className="consent"><input type="checkbox"/>Acepto la Política de Protección de Datos Personales</label><button className="action action-filled" disabled type="submit">Enviar Consulta</button></fieldset><p className="form-notice" id="form-unavailable">El formulario estará disponible próximamente.</p></form><p className="response-time">El Comité de Ética acusará recibo dentro de los 5 días hábiles y comunicará el resultado de la investigación dentro de los plazos establecidos en el Código de Ética y en la Res. N.° 2/2021 BCP.</p></div></div></section></>;
}
