import { notFound } from 'next/navigation';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { DocumentList, NormativeDocuments } from '@/components/document-list';
import { ReportsContent, ComplaintsContent, ClaimsManagementContent } from '@/components/transparency-extras';
import policies from '@/lib/transparency-data.json';
const slugs=[...Object.keys(policies),'denuncias','gobierno-corporativo','gestion-reclames','normativas','informes'];
export function generateStaticParams(){return slugs.map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=policies[slug as keyof typeof policies];const titles:Record<string,string>={'denuncias':'Canal de Denuncias','gobierno-corporativo':'Gobierno Corporativo','gestion-reclames':'Gestión de Reclames','normativas':'Leyes, normativas y resoluciones vigentes','informes':'Gobierno Corporativo'};return {title:`${page?.title??titles[slug]??'Transparencia'} — GS3`};}
export default async function TransparencyPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;if(!slugs.includes(slug))notFound();
 const page=policies[slug as keyof typeof policies];const titles:Record<string,string>={'denuncias':'Canal de Denuncias','gobierno-corporativo':'Gobierno Corporativo','gestion-reclames':'Gestión de Reclames','normativas':'Leyes, normativas y resoluciones vigentes'};const title=page?.title??titles[slug];const isNormative=slug==='normativas';const isClaims=slug==='gestion-reclames';
 return <><SiteHeader/><main className={`transparency-page${isNormative?' normative-page':''}${isClaims?' claims-page':''}`}><div className="transparency-banner"><img src="/assets/transparency-header.png" alt="Cosechadoras trabajando en el campo al atardecer" fetchPriority="high"/></div><div className="transparency-content"><div className={`page-heading${isNormative?' normative-heading':''}`}><p className="eyebrow">{isNormative||isClaims?'Informes':'Transparencia'}</p><h1>{title}</h1></div>{page&&<><div className="policy-intro">{page.intro.map(p=><p key={p}>{p}</p>)}</div><div className="policy-sections">{page.sections.map(section=><section className="policy-row" key={section.title}><h2>{section.title}</h2><div>{section.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div></section>)}</div></>}{['gobierno-corporativo','informes'].includes(slug)&&<ReportsContent/>}{slug==='denuncias'&&<ComplaintsContent/>}{isClaims&&<ClaimsManagementContent/>}{isNormative&&<NormativeDocuments/>}{!isNormative&&(page||['tasas','gobierno-corporativo','informes','denuncias','gestion-reclames'].includes(slug))&&<DocumentList multiple={slug==='tasas'} year={['tasas','informes','denuncias','gestion-reclames'].includes(slug)}/>}</div><div className="bottom-wrap"><SiteFooter/></div></main></>;
}
